version: '3.8'

services:


   

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    # image: mysql:8.1
    container_name: mysql-container
    restart: always
    # hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_TCP_PORT: 33061
    
    ports:
      - "33061:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/Dump20240805.sql:/docker-entrypoint-initdb.d/init.sql


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    # links:
    #   - mysql
    environment:

      GEMINI_API_KEY:  ${GEMINI_API_KEY}
  
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      hf_token: ${hf_token}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      COHERE_API_KEY: ${COHERE_API_KEY}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      MYSQL_PASS: ${MYSQL_PASS}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      GOOGLE_MAPS_API: ${GOOGLE_MAPS_API}
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # command: sh -c "dockerize -wait tcp://db:33061 -timeout 300s -wait-retry-interval 30s /sayhello"
    volumes:
      - ./api:/code



  # hf_spaces_app:
  #   build:
  #     context: ./hf_spaces_app
  #     dockerfile: Dockerfile
  #   container_name: hf_spaces_app-container
  #   ports:
  #     - "7860:7860"
  #   depends_on:
  #     - mysql
  #     - api

    # volumes:
    #   - ./api:/code


# volumes:
#   db:
#     driver: local

volumes:
  mysql:
    driver: local